/*
 * Samuel Bulnes
 * Senior Project
 * Chat Model
 * Defines the structure of a chat conversation stored in Firestore
 */

import 'package:cloud_firestore/cloud_firestore.dart';

//***********************************************************************************
// Stores participant information, last message preview, and activity timestamp
class Chat {
  final String id;                           // chat document ID (auto-generated by Firestore)
  final List<String> participantIds;         // Array of two user IDs in this chat
  final Map<String, String> participantNames;// Map of userId → userName for quick lookup
  final String? jobId;                       // Optional: ID of the job this chat is about
  final String? jobTitle;                    // Optional: title of the related job
  final String lastMessage;                  // Preview text of the most recent message
  final String lastSenderId;                 // UID of who sent the last message
  final DateTime updatedAt;                  // Timestamp of last activity in this chat
  final int unreadCount;                     // Number of unread messages for current user

  Chat({
    required this.id,
    required this.participantIds,
    required this.participantNames,
    this.jobId,
    this.jobTitle,
    required this.lastMessage,
    required this.lastSenderId,
    required this.updatedAt,
    this.unreadCount = 0,                     // Default to 0 unread messages
  });

  //***********************************************************************************
  // Convert to Map for Firestore
  Map<String, dynamic> toMap() {
    return {
      'participantIds': participantIds,
      'participantNames': participantNames,
      'jobId': jobId,
      'jobTitle': jobTitle,
      'lastMessage': lastMessage,
      'lastSenderId': lastSenderId,
      'updatedAt': Timestamp.fromDate(updatedAt), // Convert DateTime to Firestore Timestamp
    };
  }

  //***********************************************************************************
  // Create from Firestore
  // Factory constructor that creates a Chat from a Firestore DocumentSnapshot
  factory Chat.fromFirestore(DocumentSnapshot doc) {
    Map<String, dynamic> data = doc.data() as Map<String, dynamic>;
    
    // Safe timestamp handling
    DateTime updatedAt;
    try {
      final timestampData = data['updatedAt'];
      if (timestampData != null && timestampData is Timestamp) {
        updatedAt = timestampData.toDate();
      } else {
        updatedAt = DateTime.now(); // Default value if null
      }
    } catch (e) {
      updatedAt = DateTime.now();
    }
    
    return Chat(
      id: doc.id,    // Document ID from Firestore
      participantIds: List<String>.from(data['participantIds'] ?? []), // Convert to typed list
      participantNames: Map<String, String>.from(data['participantNames'] ?? {}), // Convert to typed map
      jobId: data['jobId'],
      jobTitle: data['jobTitle'],
      lastMessage: data['lastMessage'] ?? '',
      lastSenderId: data['lastSenderId'] ?? '',
      updatedAt: updatedAt,
      unreadCount: 0, // Calculated later
    );
  }

  //***********************************************************************************
  // Get other participant's name
  String getOtherUserName(String currentUserId) {
    final otherUserId = participantIds.firstWhere(
      (id) => id != currentUserId,
      orElse: () => '',
    );
    return participantNames[otherUserId] ?? 'Unknown User';
  }

  //***********************************************************************************
  // Get other participant's ID
  String getOtherUserId(String currentUserId) {
    return participantIds.firstWhere(
      (id) => id != currentUserId,
      orElse: () => '',
    );
  }

  //***********************************************************************************
  // Copy with modifications
  Chat copyWith({
    String? id,
    List<String>? participantIds,
    Map<String, String>? participantNames,
    String? jobId,
    String? jobTitle,
    String? lastMessage,
    String? lastSenderId,
    DateTime? updatedAt,
    int? unreadCount,
  }) {
    return Chat(
      id: id ?? this.id,
      participantIds: participantIds ?? this.participantIds,
      participantNames: participantNames ?? this.participantNames,
      jobId: jobId ?? this.jobId,
      jobTitle: jobTitle ?? this.jobTitle,
      lastMessage: lastMessage ?? this.lastMessage,
      lastSenderId: lastSenderId ?? this.lastSenderId,
      updatedAt: updatedAt ?? this.updatedAt,
      unreadCount: unreadCount ?? this.unreadCount,
    );
  }
}