/*
 * Samuel Bulnes
 * Senior Project
 * Message Model
 * Defines the structure of a single chat message stored in Firestore
 */

import 'package:cloud_firestore/cloud_firestore.dart';

//***********************************************************************************
// Each message belongs to a specific chat and is sent by a specific user
class Message {
  final String id;          // Message ID (auto-generated by Firestore)
  final String chatId;      // ID of the parent chat this message belongs to
  final String senderId;    // Firebase UID of who sent this message
  final String senderName;  // Display name of the sender
  final String text;        // The actual message content
  final DateTime timestamp; // When the message was sent
  final bool isRead;        // Whether the receiver has read this message

  Message({
    required this.id,
    required this.chatId,
    required this.senderId,
    required this.senderName,
    required this.text,
    required this.timestamp,
    this.isRead = false,
  });

  //*********************************************************************************
  // Convert to Map for Firestore
  Map<String, dynamic> toMap() {
    return {
      'chatId': chatId,
      'senderId': senderId,
      'senderName': senderName,
      'text': text,
      'timestamp': Timestamp.fromDate(timestamp), // Convert DateTime to Firestore Timestamp
      'isRead': isRead,
    };
  }

  //*********************************************************************************
  // Create from Firestore
  // Factory constructor that creates a Message from a Firestore DocumentSnapshot
  factory Message.fromFirestore(DocumentSnapshot doc) {
    Map<String, dynamic> data = doc.data() as Map<String, dynamic>;
    
    // Safe timestamp handling
    DateTime timestamp;
    try {
      final timestampData = data['timestamp'];
      if (timestampData != null && timestampData is Timestamp) {
        timestamp = timestampData.toDate();  // Convert Firestore Timestamp to DateTime
      } else {
        timestamp = DateTime.now();          // Use current time as fallback
      }
    } catch (e) {
      timestamp = DateTime.now();            // Use current time if any error occurs
    }
    
    return Message(
      id: doc.id,                                  // Document ID from Firestore
      chatId: data['chatId'] ?? '',
      senderId: data['senderId'] ?? '',
      senderName: data['senderName'] ?? 'Unknown', // Default name if missing
      text: data['text'] ?? '',
      timestamp: timestamp,
      isRead: data['isRead'] ?? false,             // Default to unread if missing
    );
  }

  //*********************************************************************************
  // Copy with modifications
  // Creates a new Message with optionally updated fields

  Message copyWith({
    String? id,
    String? chatId,
    String? senderId,
    String? senderName,
    String? text,
    DateTime? timestamp,
    bool? isRead,
  }) {
    return Message(
      id: id ?? this.id,
      chatId: chatId ?? this.chatId,
      senderId: senderId ?? this.senderId,
      senderName: senderName ?? this.senderName,
      text: text ?? this.text,
      timestamp: timestamp ?? this.timestamp,
      isRead: isRead ?? this.isRead,
    );
  }
}