// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Provides default Firebase configuration options for each platform.
///
/// This file is automatically generated when running:
///   flutterfire configure
///
/// Usage example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// The `currentPlatform` getter determines which set of credentials to load
/// depending on the platform where the app is running (Android, iOS, Web, etc.).
class DefaultFirebaseOptions {
  
  /// Returns the correct FirebaseOptions object for
  /// the platform the app is currently running on.
  static FirebaseOptions get currentPlatform {
    // Web takes priority because `defaultTargetPlatform` is not used for web.
    if (kIsWeb) {
      return web;
    }

    // Select matching options for each platform
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        // Linux platform is unsupported by default
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run FlutterFire CLI again to configure this platform.',
        );

      default:
        // Should never happen but included for safety
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ===========================================================================
  // WEB CONFIGURATION
  // Used when running the Flutter web version of the app.
  // ===========================================================================

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi_v5dOcJlj5tITxYRXYX1jL7xxp877s0',
    appId: '1:588133544931:web:cecba769579a4940d266d6',
    messagingSenderId: '588133544931',
    projectId: 'ineed-oru-1',
    authDomain: 'ineed-oru-1.firebaseapp.com',
    storageBucket: 'ineed-oru-1.firebasestorage.app',
  );

  // ===========================================================================
  // ANDROID CONFIGURATION
  // Pulled from your google-services.json file.
  // ===========================================================================

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnvsLgx-wXWWnpbMRoFdMmuv6wDc3bAIs',
    appId: '1:588133544931:android:6b4191a2eb51f0dad266d6',
    messagingSenderId: '588133544931',
    projectId: 'ineed-oru-1',
    storageBucket: 'ineed-oru-1.firebasestorage.app',
  );

  // ===========================================================================
  // IOS CONFIGURATION
  // Pulled from your GoogleService-Info.plist file.
  // ===========================================================================

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0YZUm4IO42Oc0DlzyLXzBKjcQvCDLcYk',
    appId: '1:588133544931:ios:e0ad09755aa13c08d266d6',
    messagingSenderId: '588133544931',
    projectId: 'ineed-oru-1',
    storageBucket: 'ineed-oru-1.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  // ===========================================================================
  // MACOS CONFIGURATION
  // Uses the same credentials as iOS (because macOS also uses plist-style config)
  // ===========================================================================

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0YZUm4IO42Oc0DlzyLXzBKjcQvCDLcYk',
    appId: '1:588133544931:ios:e0ad09755aa13c08d266d6',
    messagingSenderId: '588133544931',
    projectId: 'ineed-oru-1',
    storageBucket: 'ineed-oru-1.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  // ===========================================================================
  // WINDOWS CONFIGURATION
  // Used by Flutter desktop builds.
  // ===========================================================================

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi_v5dOcJlj5tITxYRXYX1jL7xxp877s0',
    appId: '1:588133544931:web:092623079091ff96d266d6',
    messagingSenderId: '588133544931',
    projectId: 'ineed-oru-1',
    authDomain: 'ineed-oru-1.firebaseapp.com',
    storageBucket: 'ineed-oru-1.firebasestorage.app',
  );
}
